### ISSUE TITLE
Blocked apps are shown in notification bar, although in app detail page "disable log notification" is enabled

### ISSUE THREAD

**Issue by 9jS2PL5T** [ukanth/afwall#1186]
Since 3.5.0 i get a notification of blocked apps in the notification bar, altough i checked the "disable log notification" box for some apps. In my example i get this notification for the Samsung keyboard app. 
Another hint: I can see the ip adresses in the notification bar, altough i don't have the donate version.

**Comment by brbsix** [comment]
I have the donate version and have been experiencing the same issue for months. It's quite annoying but I haven't disabled notifications for the entire AFWall app because there are certain blocked apps that I would still like to see firewall notifications for. I don't recall exactly when it began happening but I am in the Play Store beta program so presumably after the AFWall+ 3.5.0 Beta 1 release in September 2020.

**Comment by ukanth** [comment]
It's quite easier to fix it, but it's a trade off between how quick you wanna see the notification vs filter the notification and then show it after few secs. I have been trying to optimize it before enabling it. It should get fixed in the upcoming versions

**Comment by MrEngineerMind** [comment]
I too see this issue in 3.5.2.

**Comment by 9jS2PL5T** [comment]
For me it's fixed in 3.5.2

**Comment by selurvedu** [comment]
I can't get rid of notifications for GPS getting blocked in v3.5.2.1. I had to disable the log service.

**Comment by The-H23** [comment]
The same issue here. I'm on v3.5.2. The option in the app detail page "disable log notification" doesn't have an effect. I still get notifications of blocked requests from those apps. I'm on a stock ROM and have a bunch of bloatware (all as system apps) I would like to block. 
I'm running in whitelist mode. Unfortunately I get spammed with all this notifications I can't see the important stuff. I had to disable the log service.

**Comment by MrEngineerMind** [comment]
I know if you reboot the device, it will fix the problem.

But I think if you do a manual "Apply Rules" in the app, that might also fix the issue.

**Comment by The-H23** [comment]
> I know if you reboot the device, it will fix the problem.
> But I think if you do a manual "Apply Rules" in the app, that might also fix the issue.

Unfortunately it doesn't work in any way. As soon as I turn on the log service in whitelist mode (allow selected) I get spammed by blocked (unchecked) apps in the notification bar, although I checked the "disable log notification" box for this particular app. The Youtube app is really verbose. I don't care about delays. Even if filtering causes some, I would be happy to have this feature. I don't need instant notifications.
